CREATE TABLE IF NOT EXISTS employee (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	fio VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS job (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	task VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS report (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	date DATE NOT NULL,
	employee_id BIGINT NOT NULL,
	job_id BIGINT NOT NULL,
	time INT NOT NULL,
	FOREIGN KEY (employee_id) REFERENCES employee(id)
		ON DELETE CASCADE,
	FOREIGN KEY (job_id) REFERENCES job(id)
		ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_report_date ON report (date);
